version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_catalog
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  materialize:
    image: materialize/materialized:latest
    container_name: materialize_db
    command: 
      - --workers=1
    ports:
      - "6875:6875"
      - "6876:6876"
    environment:
      MZ_WORKERS: 1
    volumes:
      - materialize_data:/var/lib/materialize
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  materialize_data: